theme: jekyll-theme-minimal
title: Conrad Ronk
description: Portfolio Site
show_downloads: False
navigation:
  - title: Home
    url: conradronk.github.io/
  - title: Transit Exploration
    url: /Transit-Data-Exploration/
